### ISSUE TITLE
Using a Custom Model (or Models) on Magic Leap 2

### ISSUE THREAD

**Issue by ThisisSaron** [LocalJoost/YoloHolo#13]
Hi!

I wanted to implement your code on a Magic Leap 2 application. Could you please let me know which parts of the code to change to implement a custom model? And which script should I change to change the labeling on the tag? Is there a character limit?

I'm also looking at training multiple models to use in different parts of the application (so that the minimumProbability can be set at a higher number without risk for false detections). Would this work with your implementation of YOLO? Or is the model only loaded once when the application is run? 

Sorry for the many questions, any help would be appreciated! I love your work :)

**Comment by LocalJoost** [comment]
Thank you. Have you, I by any chance, I seen this article on my blog? https://localjoost.github.io/Running-a-YoloV8-model-on-a-Magic-Leap-2-to-recognize-objects-in-3D-space/

**Comment by ThisisSaron** [comment]
Yes, I have. I downloaded the project file for Magic Leap 2 and have been looking through the various scripts to find where it accesses the ONNX file. I'm not too familiar with C# but it seemed like Line 11 of YoloProcessorProfile.cs was where you'd make the change for a custom model. Is this correct? And if so, is menuName for the Translator file and fileName for the ONNX model? 

Thanks for the quick reply

**Comment by LocalJoost** [comment]
Hi @ThisisSaron, if you look into my various Yolo blogs you might be able to piece this together yourself, but I hope to save you some time by these images:

If you want to use a different model, just drag in into the Model field of the YoloV8ProcessorProfile.
<img width="569" alt="image" src="https://github.com/LocalJoost/YoloHolo/assets/4129183/bbb370d9-4dc8-491e-a3f7-b9e4b783999a">
If you want the classes correctly translated, you will need to make a Translator file. Samples are DemoModelTranslator and V8AirplaneTranslator. They need to implement IYoloClassTranslator. The list is 0 based, so if we take DemoModelTranslator , class 0 is "person", class 1 is "bicycle", class 2 is "car", etc. The V8AirplaneTranslator only has one class, number 0, "airplane",  because the model recognizes only one type of object. The exact values and order of values depend on your model. Once you created a Translator, you should be able to select it from the drop down in the processor profile:
![image](https://github.com/LocalJoost/YoloHolo/assets/4129183/7148b474-11d2-4f4c-926e-7c5d51aa92df)

So you can swap out your model with changing _very_ little code.

Caveats: HoloLens 2 is a powerful spatial computer, but it does not have much power to spare for _other_ things. Performance goes down the drain pretty quickly if you take larger Yolo models. I used the very, very smallest (nano) models, and I could get about 3-4 recognitions per second. See here for how I created my custom model. https://localjoost.github.io/HoloLens-AI-training-a-YoloV8-model-locally-on-custom-pictures-to-recognize-objects-in-3D-space/ 
Also, the model's image size is very small (320x256) so any images you feed to it should be scaled down to that.

Good luck!

**Comment by ThisisSaron** [comment]
Okay, thank you. I didn't realize it could be done through the GUI on the asset. I really appreciate your help!
